general {
    lock_cmd = pidof hyprlock || hyprlock
    unlock_cmd = killall hyprlock
}

# Auto lock after 10 minutes (change if needed)
listener {
    timeout = 600
    on-timeout = pidof hyprlock || hyprlock
}

